algoritmo "Soma"
//Nome: Gabriel Jesus
//Data: 23/10/2024

// 04)Desenvolva um algoritmo que leia dois números inteiros e mostre o somatório entre eles.

var
   //Declaração das variáveis
   N1, N2, soma: inteiro

inicio
   //Leitura
   Escreva("Digite um número: ")
   leia(N1)
   Escreva("Digite outro número: ")
   leia(N2)
   
   //Processamento e Apresentação
   soma <- N1 + N2
   Escreva("A soma é:", soma)

fimalgoritmo